{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8s-dashboard-proxy.serviceAccountName" . }}
  {{- if .Values.serviceAccount.roleARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN }}
  {{- end }}
  labels:
{{ include "k8s-dashboard-proxy.labels" . | indent 4 }}
{{- end -}}
