name: k8s-dashboard-proxy-deploy

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm build and deploy
      run: |
        # Build
        npm install
        npm install -g browserify
        browserify public/javascripts/tokenlib.js > public/javascripts/bundle.js
        docker build .  --tag gonitro/k8s-dashboard-proxy:$(git rev-parse --short HEAD)
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        docker push gonitro/k8s-dashboard-proxy:$(git rev-parse --short HEAD)
