name: k8s-dashboard-proxy-ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .  --tag gonitro/k8s-dashboard-proxy:$(git rev-parse --short HEAD) && docker push gonitro/k8s-dashboard-proxy:$(git rev-parse --short HEAD)
