name: k8s-dashboard-proxy-test

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: '10.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and lint
      run: |
        # Build and test the project
        npm install
        npm run lint --if-present
        npm audit
        npm run test
